
project:
  type: website
  output-dir: docs
  resources: 
    - "/*.zip"

execute:
  freeze: auto
  cache: true

website:
  title: BiU Statistikvorlesung WiSe 2025-2026
  navbar: 
    pinned: true
  sidebar:
    #  logo: img/logosquare.svg
    contents:
      - index.qmd
      - Methodologie.qmd
      - Messtheorie.qmd
      - Univariate Deskriptivstatistik.qmd
      - Einfache lineare Regression.qmd
      - Multiple lineare Regression.qmd


format:
  html:
    toc: true
    toc-depth: 3
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300     
    css: 
      - brand.css     
      - exams/webex.css
    include-after-body: exams/webex.js

brand:
  color:
    link: "#267326"
  logo: 
    medium: "img/logo_standard.svg"  

lang: de
bibliography: skeleton.bib
csl: apa.csl
